Add vulnerabilities to the Github Datasource
grafana/github-datasource pull request #176
Opened 2022-07-27 20:51 UTC by timlevett

GitHub added vulnerability (dependabot) alerts as something you can query via the API so this enhancement lets you query that from the GitHub Datasource in Grafana.

Note this was done as part of a hackathon in 2021. I just rebased off of main and retested. Seemed to work.

2022-07-28 19:29 UTC, bossinc requested changes
It looks like the linter is complaining about a few Go functions not having comments, but other than that it looks good! 👍 🥳

2022-07-29 20:29 UTC, timlevett commented
Fixed linting issues (3rd time is the charm 😅 )

2022-07-29 21:25 UTC, kminehart approved these changes

2022-07-29 21:26 UTC, bossinc approved these changes

2022-07-30 01:19 UTC, merged