Add feature tracking
grafana/github-datasource pull request #248
Opened 2023-09-04 11:21 UTC by gwdawson

track executed queries so we can view some stats around the datasource
this includes but not limited to:
- how many queries are sent
- how often are each query types used
- ...

2023-09-04 13:36 UTC, zoltanbedi reviewed
This feels expensive. I'd rather use the dashboardLoaded event like we do in azure monitor https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/azuremonitor/module.ts#L24 so it won't create a new entry for every query run. WDYT?

2023-09-05 15:47 UTC, gwdawson commented
based on what we discussed in todays standup, it seems we are happy to continue with my proposed solution.

2023-09-06 11:38 UTC, zoltanbedi requested changes

2023-09-06 11:38 UTC, zoltanbedi commented on src/DataSource.ts
> +        properties['timeField'] = issueTimeFieldReference[target.options?.timeField ?? 0];
I like how you don't just toss in the number here however this approach is not error prone. What if someone adds a new enum value to any of the types there? Your code will break.

Instead you can use https://www.typescriptlang.org/docs/handbook/enums.html#reverse-mappings
like:
`IssueTimeField[target.options?.timeField ?? 0];`

Can you please also extract this reporting logic to its own function?
Any reason you are accessing the timeField property as an index signature?

2023-09-07 09:43 UTC, zoltanbedi approved these changes
LGTM

2023-09-07 09:52 UTC, merged